### ISSUE TITLE
Error: Cannot find module 'dayjs'

### ISSUE THREAD

**Issue by x1737886903** [mrabit/xmtravel#13]
## 开始执行... 2022-08-03 19:30:07

🔔小茅运旅行, 开始!
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module 'dayjs'
Require stack:
- /ql/scripts/mrabit_xmtravel/api.js
- /ql/scripts/mrabit_xmtravel/qlAction.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/ql/scripts/mrabit_xmtravel/api.js:2:15)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/ql/scripts/mrabit_xmtravel/api.js',
    '/ql/scripts/mrabit_xmtravel/qlAction.js'
  ]
}

## 执行结束... 2022-08-03 19:30:09 耗时 2 秒

**Comment by x1737886903** [comment]
> ## 开始执行... 2022-08-03 19:30:07
> 🔔小茅运旅行, 开始! node:internal/modules/cjs/loader:936 throw err; ^
> 
> Error: Cannot find module 'dayjs' Require stack:
> 
> * /ql/scripts/mrabit_xmtravel/api.js
> * /ql/scripts/mrabit_xmtravel/qlAction.js
>   at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
>   at Function.Module._load (node:internal/modules/cjs/loader:778:27)
>   at Module.require (node:internal/modules/cjs/loader:1005:19)
>   at require (node:internal/modules/cjs/helpers:102:18)
>   at Object. (/ql/scripts/mrabit_xmtravel/api.js:2:15)
>   at Module._compile (node:internal/modules/cjs/loader:1101:14)
>   at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
>   at Module.load (node:internal/modules/cjs/loader:981:32)
>   at Function.Module._load (node:internal/modules/cjs/loader:822:12)
>   at Module.require (node:internal/modules/cjs/loader:1005:19) {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: [
>   '/ql/scripts/mrabit_xmtravel/api.js',
>   '/ql/scripts/mrabit_xmtravel/qlAction.js'
>   ]
>   }
> 
> ## 执行结束... 2022-08-03 19:30:09 耗时 2 秒

运行环境：arm框架的玩客云，青龙运行

**Comment by mrabit** [comment]
青龙面板运行需要手动安装依赖: axios、dayjs和colors

依赖管理 -> 新建依赖
