### ISSUE TITLE
运行报错,const xmTravelAxios = axios.create()   TypeError: Cannot read properties of undefined (reading 'create')

### ISSUE THREAD

**Issue by augusl** [mrabit/xmtravel#17]
## 开始执行... 2022-10-11 10:58:18

🔔小茅运旅行, 开始!
/ql/data/scripts/mrabit_xmtravel/api.js:24
const xmTravelAxios = axios.create()
                            ^

TypeError: Cannot read properties of undefined (reading 'create')
    at Object.<anonymous> (/ql/data/scripts/mrabit_xmtravel/api.js:24:29)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/ql/data/scripts/mrabit_xmtravel/qlAction.js:5:13)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)

## 执行结束... 2022-10-11 10:58:19 耗时 1 秒

**Comment by jie1192555084** [comment]
确实报错了，换了几个服务器，本地都是这个错误
